//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model()
        {
            this.Category_Model = new HashSet<Category_Model>();
        }
    
        public string MODEL_ID { get; set; }
        public string MODEL_NAME { get; set; }
        public string MODEL_DESC { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string IMAGE_ID { get; set; }
        public string EXTENDED_DESC { get; set; }
        public string KEYWORDS { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public Nullable<float> CURRENT_STATUS { get; set; }
        public string MODEL_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Model> Category_Model { get; set; }
    }
}
