//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_product
    {
        public string model_name { get; set; }
        public string part_no { get; set; }
        public string relation { get; set; }
        public string seq_num { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string Last_update_by { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> Last_update_date { get; set; }
        public string desc_com { get; set; }
    }
}
