//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAdvantechEntities : DbContext
    {
        public MyAdvantechEntities()
            : base("name=MyAdvantechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual DbSet<order_Master_ExtensionV2> order_Master_ExtensionV2 { get; set; }
        public virtual DbSet<ORDER_MASTER> ORDER_MASTER { get; set; }
        public virtual DbSet<ORDER_MASTER_EXTENSION> ORDER_MASTER_EXTENSION { get; set; }
        public virtual DbSet<ORDER_PARTNERS> ORDER_PARTNERS { get; set; }
        public virtual DbSet<TIMEZONE> TIMEZONE { get; set; }
    }
}
