//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_Master_ExtensionV2
    {
        public string ORDER_ID { get; set; }
        public int PI2CUSTOMER_FLAG { get; set; }
        public int OrderNoScheme { get; set; }
    }
}
