//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_MASTER
    {
        public string ORDER_ID { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_TYPE { get; set; }
        public string PO_NO { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public string SOLDTO_ID { get; set; }
        public string SHIPTO_ID { get; set; }
        public string BILLTO_ID { get; set; }
        public string SALES_ID { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string ATTENTION { get; set; }
        public string PARTIAL_FLAG { get; set; }
        public string COMBINE_ORDER_FLAG { get; set; }
        public string EARLY_SHIP_FLAG { get; set; }
        public Nullable<decimal> FREIGHT { get; set; }
        public Nullable<decimal> INSURANCE { get; set; }
        public string REMARK { get; set; }
        public string PRODUCT_SITE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> REQUIRED_DATE { get; set; }
        public string SHIPMENT_TERM { get; set; }
        public string SHIP_VIA { get; set; }
        public string CURRENCY { get; set; }
        public string ORDER_NOTE { get; set; }
        public string ORDER_STATUS { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<int> TOTAL_LINE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string CUSTOMER_ATTENTION { get; set; }
        public string AUTO_ORDER_FLAG { get; set; }
        public string INCOTERM { get; set; }
        public string INCOTERM_TEXT { get; set; }
        public string SALES_NOTE { get; set; }
        public string OP_NOTE { get; set; }
        public string SHIP_CONDITION { get; set; }
        public string NONERoHS_ACCEPT { get; set; }
        public string ProjectFlag { get; set; }
        public string Z7Sales { get; set; }
        public string DefaultSalesNote { get; set; }
        public string prj_Note { get; set; }
        public string EARLY_SHIP { get; set; }
        public string ER_EMPLOYEE { get; set; }
        public string END_CUST { get; set; }
        public string KEYPERSON { get; set; }
        public string CREDIT_CARD { get; set; }
        public Nullable<System.DateTime> CREDIT_CARD_EXPIRE_DATE { get; set; }
        public string CREDIT_CARD_VERIFY_NUMBER { get; set; }
        public string PAYTERM { get; set; }
        public string CREDIT_CARD_HOLDER { get; set; }
        public string CREDIT_CARD_TYPE { get; set; }
        public string BILLINGINSTRUCTION_INFO { get; set; }
        public string EMPLOYEEID { get; set; }
        public string DIST_CHAN { get; set; }
        public string DIVISION { get; set; }
        public string SALESGROUP { get; set; }
        public string SALESOFFICE { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<int> IS_EARLYSHIP { get; set; }
        public Nullable<int> isExempt { get; set; }
    }
}
