//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_PRODUCT
    {
        public string PART_NO { get; set; }
        public string MODEL_NO { get; set; }
        public string MATERIAL_GROUP { get; set; }
        public string DIVISION { get; set; }
        public string PRODUCT_HIERARCHY { get; set; }
        public string PRODUCT_GROUP { get; set; }
        public string PRODUCT_DIVISION { get; set; }
        public string PRODUCT_LINE { get; set; }
        public string GENITEMCATGRP { get; set; }
        public string PRODUCT_DESC { get; set; }
        public string ROHS_FLAG { get; set; }
        public string STATUS { get; set; }
        public string EGROUP { get; set; }
        public string EDIVISION { get; set; }
        public Nullable<double> NET_WEIGHT { get; set; }
        public Nullable<double> GROSS_WEIGHT { get; set; }
        public string WEIGHT_UNIT { get; set; }
        public Nullable<double> VOLUME { get; set; }
        public string VOLUME_UNIT { get; set; }
        public string CREATE_DATE { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string GIP_CODE { get; set; }
        public string SIZE_DIMENSIONS { get; set; }
        public string SOURCE_LOCATION { get; set; }
        public string PRODUCT_FAMILY { get; set; }
        public string PLM_STATUS { get; set; }
    }
}
