//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_COMPANY_PARTNERS
    {
        public string COMPANY_ID { get; set; }
        public string ORG_ID { get; set; }
        public string DIST_CHANN { get; set; }
        public string DIVISION { get; set; }
        public string PARTNER_FUNCTION { get; set; }
        public string PARENT_COMPANY_ID { get; set; }
        public string VENDOR_CREDITOR { get; set; }
        public string SALES_CODE { get; set; }
        public string PARTNER_NUMBER { get; set; }
        public string KNREF { get; set; }
        public string DEFPA { get; set; }
        public int ID { get; set; }
    }
}
