//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_PRODUCT_STATUS
    {
        public string PART_NO { get; set; }
        public string SALES_ORG { get; set; }
        public string DIST_CHANNEL { get; set; }
        public string PRODUCT_STATUS { get; set; }
        public Nullable<decimal> MIN_ORDER_QTY { get; set; }
        public Nullable<decimal> MIN_DLV_QTY { get; set; }
        public Nullable<decimal> MIN_BTO_QTY { get; set; }
        public string DLV_PLANT { get; set; }
        public string MATERIAL_PRICING_GRP { get; set; }
        public string VALID_DATE { get; set; }
        public string ITEM_CATEGORY_GROUP { get; set; }
        public long ID { get; set; }
    }
}
