//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_DIMCOMPANY
    {
        public string UNIQUE_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public string ORG_ID { get; set; }
        public string PARENTCOMPANYID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string FAX_NO { get; set; }
        public string TEL_NO { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string PRICE_CLASS { get; set; }
        public string CURRENCY { get; set; }
        public string COUNTRY { get; set; }
        public string REGION_CODE { get; set; }
        public string ZIP_CODE { get; set; }
        public string CITY { get; set; }
        public string ATTENTION { get; set; }
        public string CREDIT_TERM { get; set; }
        public string SHIP_VIA { get; set; }
        public string URL { get; set; }
        public string CREATEDDATE { get; set; }
        public string CREATED_BY { get; set; }
        public string COMPANY_PRICE_TYPE { get; set; }
        public string SHIPCONDITION { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string SALESOFFICE { get; set; }
        public string SALESGROUP { get; set; }
        public Nullable<decimal> AMT_INSURED { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string DELETION_FLAG { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string SALESOFFICENAME { get; set; }
        public string SAP_SALESNAME { get; set; }
        public string SAP_SALESCODE { get; set; }
        public string SAP_ISNAME { get; set; }
        public string SAP_OPNAME { get; set; }
        public string SECTOR { get; set; }
        public string PRIMARY_BAA { get; set; }
        public string ACCOUNT_ROW_ID { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public string RBU { get; set; }
        public string PRIMARY_SALES_EMAIL { get; set; }
        public string PRIMARY_OWNER_DIVISION { get; set; }
        public string BUSINESS_GROUP { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public Nullable<decimal> FACT2005 { get; set; }
        public Nullable<decimal> FACT2006 { get; set; }
        public Nullable<decimal> FACT2007 { get; set; }
        public Nullable<decimal> FACT2008 { get; set; }
        public Nullable<decimal> FACT2009 { get; set; }
        public Nullable<decimal> FACT2010 { get; set; }
        public Nullable<System.DateTime> LAST_BUY_DATE { get; set; }
        public Nullable<int> ORDERS_IN_PAST_YEAR { get; set; }
        public Nullable<decimal> AMOUNT_IN_PAST_YEAR { get; set; }
        public Nullable<int> ORDERS_IN_PAST_HALFYEAR { get; set; }
        public string CUST_IND { get; set; }
        public string VM { get; set; }
        public string PRICE_GRP { get; set; }
        public string PRICE_LIST { get; set; }
        public string INCO1 { get; set; }
        public string INCO2 { get; set; }
        public string PAYMENT_TERM_CODE { get; set; }
        public string PAYMENT_TERM_NAME { get; set; }
        public int ID { get; set; }
    }
}
