//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Advantech.Myadvantech.DataAccess.WSSiebel_AddAccount {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ADVWebService-AddAccount", Namespace="http://siebel.com/CustomUI")]
    public partial class ADVWebServiceAddAccount : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ADVWebServiceAddAccount() {
            this.Url = global::Advantech.Myadvantech.DataAccess.Properties.Settings.Default.Advantech_Myadvantech_DataAccess_UpdOppty_ADVWebService_UpdOppty;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddAccountCompletedEventHandler AddAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/http://siebel.com/CustomUI:AddAccount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddAccount_Output", Namespace="http://siebel.com/CustomUI")]
        public AddAccount_Output AddAccount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://siebel.com/CustomUI")] AddAccount_Input AddAccount_Input) {
            object[] results = this.Invoke("AddAccount", new object[] {
                        AddAccount_Input});
            return ((AddAccount_Output)(results[0]));
        }
        
        /// <remarks/>
        public void AddAccountAsync(AddAccount_Input AddAccount_Input) {
            this.AddAccountAsync(AddAccount_Input, null);
        }
        
        /// <remarks/>
        public void AddAccountAsync(AddAccount_Input AddAccount_Input, object userState) {
            if ((this.AddAccountOperationCompleted == null)) {
                this.AddAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAccountOperationCompleted);
            }
            this.InvokeAsync("AddAccount", new object[] {
                        AddAccount_Input}, this.AddAccountOperationCompleted, userState);
        }
        
        private void OnAddAccountOperationCompleted(object arg) {
            if ((this.AddAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAccountCompleted(this, new AddAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class AddAccount_Input {
        
        private ACC aCCField;
        
        private string sOURCEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
        public ACC ACC {
            get {
                return this.aCCField;
            }
            set {
                this.aCCField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE {
            get {
                return this.sOURCEField;
            }
            set {
                this.sOURCEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
    public partial class ACC {
        
        private string sTATUSField;
        
        private string bUS_GROUPField;
        
        private string cURRENCYField;
        
        private string dESCField;
        
        private string eRPIDField;
        
        private string uRLField;
        
        private string iNTEGRATION_IDField;
        
        private string sITEField;
        
        private string mAIN_FAXField;
        
        private string mAIN_PHONEField;
        
        private string nAMEField;
        
        private string nDA_DATEField;
        
        private string pAR_ACC_IDField;
        
        private string iS_PARTNERField;
        
        private string dETENTIONField;
        
        private string rOW_IDField;
        
        private string tAXIDField;
        
        private string tYPEField;
        
        private ADDR[] aDDRField;
        
        private POSITION[] pOSITIONField;
        
        private ORG[] oRGField;
        
        private BAA[] bAAField;
        
        private INDUSTRY[] iNDUSTRYField;
        
        private CONTACT[] cONTACTField;
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string BUS_GROUP {
            get {
                return this.bUS_GROUPField;
            }
            set {
                this.bUS_GROUPField = value;
            }
        }
        
        /// <remarks/>
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        public string DESC {
            get {
                return this.dESCField;
            }
            set {
                this.dESCField = value;
            }
        }
        
        /// <remarks/>
        public string ERPID {
            get {
                return this.eRPIDField;
            }
            set {
                this.eRPIDField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public string INTEGRATION_ID {
            get {
                return this.iNTEGRATION_IDField;
            }
            set {
                this.iNTEGRATION_IDField = value;
            }
        }
        
        /// <remarks/>
        public string SITE {
            get {
                return this.sITEField;
            }
            set {
                this.sITEField = value;
            }
        }
        
        /// <remarks/>
        public string MAIN_FAX {
            get {
                return this.mAIN_FAXField;
            }
            set {
                this.mAIN_FAXField = value;
            }
        }
        
        /// <remarks/>
        public string MAIN_PHONE {
            get {
                return this.mAIN_PHONEField;
            }
            set {
                this.mAIN_PHONEField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string NDA_DATE {
            get {
                return this.nDA_DATEField;
            }
            set {
                this.nDA_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string PAR_ACC_ID {
            get {
                return this.pAR_ACC_IDField;
            }
            set {
                this.pAR_ACC_IDField = value;
            }
        }
        
        /// <remarks/>
        public string IS_PARTNER {
            get {
                return this.iS_PARTNERField;
            }
            set {
                this.iS_PARTNERField = value;
            }
        }
        
        /// <remarks/>
        public string DETENTION {
            get {
                return this.dETENTIONField;
            }
            set {
                this.dETENTIONField = value;
            }
        }
        
        /// <remarks/>
        public string ROW_ID {
            get {
                return this.rOW_IDField;
            }
            set {
                this.rOW_IDField = value;
            }
        }
        
        /// <remarks/>
        public string TAXID {
            get {
                return this.tAXIDField;
            }
            set {
                this.tAXIDField = value;
            }
        }
        
        /// <remarks/>
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDR")]
        public ADDR[] ADDR {
            get {
                return this.aDDRField;
            }
            set {
                this.aDDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSITION")]
        public POSITION[] POSITION {
            get {
                return this.pOSITIONField;
            }
            set {
                this.pOSITIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORG")]
        public ORG[] ORG {
            get {
                return this.oRGField;
            }
            set {
                this.oRGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BAA")]
        public BAA[] BAA {
            get {
                return this.bAAField;
            }
            set {
                this.bAAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INDUSTRY")]
        public INDUSTRY[] INDUSTRY {
            get {
                return this.iNDUSTRYField;
            }
            set {
                this.iNDUSTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTACT")]
        public CONTACT[] CONTACT {
            get {
                return this.cONTACTField;
            }
            set {
                this.cONTACTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
    public partial class ADDR {
        
        private string cITYField;
        
        private string cOUNTRYField;
        
        private string zIPField;
        
        private string sTATEField;
        
        private string lINE1Field;
        
        private string lINE2Field;
        
        private string iS_PRIMARYField;
        
        /// <remarks/>
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
            }
        }
        
        /// <remarks/>
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        public string LINE1 {
            get {
                return this.lINE1Field;
            }
            set {
                this.lINE1Field = value;
            }
        }
        
        /// <remarks/>
        public string LINE2 {
            get {
                return this.lINE2Field;
            }
            set {
                this.lINE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IS_PRIMARY {
            get {
                return this.iS_PRIMARYField;
            }
            set {
                this.iS_PRIMARYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
    public partial class CONTACT {
        
        private string cON_ROW_IDField;
        
        /// <remarks/>
        public string CON_ROW_ID {
            get {
                return this.cON_ROW_IDField;
            }
            set {
                this.cON_ROW_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
    public partial class INDUSTRY {
        
        private string nAMEField;
        
        private string cODEField;
        
        private string iS_PRIMARYField;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IS_PRIMARY {
            get {
                return this.iS_PRIMARYField;
            }
            set {
                this.iS_PRIMARYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
    public partial class BAA {
        
        private string nAMEField;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
    public partial class ORG {
        
        private string nAMEField;
        
        private string iS_PRIMARYField;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IS_PRIMARY {
            get {
                return this.iS_PRIMARYField;
            }
            set {
                this.iS_PRIMARYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVAccountIO")]
    public partial class POSITION {
        
        private string nAMEField;
        
        private string iS_PRIMARYField;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IS_PRIMARY {
            get {
                return this.iS_PRIMARYField;
            }
            set {
                this.iS_PRIMARYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class AddAccount_Output {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string rOW_IDField;
        
        private string sTATUSField;
        
        /// <remarks/>
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ROW_ID {
            get {
                return this.rOW_IDField;
            }
            set {
                this.rOW_IDField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AddAccountCompletedEventHandler(object sender, AddAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddAccount_Output Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddAccount_Output)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591