//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.1.43:8089/WSSiebel.asmx")]
        public string Advantech_Myadvantech_DataAccess_SiebelWebService_WSSiebel {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_SiebelWebService_WSSiebel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.1.43:8066/WSSiebel.asmx")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_New_WSSiebel {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_New_WSSiebel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crmap-global3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MTL&Password=MTL02DkOSq")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_AddAction_ADVWebServoce_AddAction {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_AddAction_ADVWebServoce_AddAction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crmap-global3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MYADVANTECH&Password=MYADVANTECH1234")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_AddQuote_ADVWebService_AddQuote {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_AddQuote_ADVWebService_AddQuote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.21.1.133/ws/general.asmx")]
        public string Advantech_Myadvantech_DataAccess_CPTEST_general {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_CPTEST_general"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.21.1.133/ws/general.asmx")]
        public string Advantech_Myadvantech_DataAccess_Pipeline_general {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_Pipeline_general"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://CRMAP-GLOBAL3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MYADVANTECH&Password=MYADVANTECH1234")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_AddOpty_ADVWebService_AddOppty {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_AddOpty_ADVWebService_AddOppty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://CRMAP-GLOBAL3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MYADVANTECH&Password=MYADVANTECH1234")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_UpdAccount_ADVWebService_UpdAccount {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_UpdAccount_ADVWebService_UpdAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://CRMAP-GLOBAL3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MYADVANTECH&Password=MYADVANTECH1234")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_AddAccount_ADVWebService_AddAccount {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_AddAccount_ADVWebService_AddAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://CRMAP-GLOBAL3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MYADVANTECH&Password=MYADVANTECH1234")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_AddContact_ADVWebService_AddContact {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_AddContact_ADVWebService_AddContact"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://CRMAP-GLOBAL3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MYADVANTECH&Password=MYADVANTECH1234")]
        public string Advantech_Myadvantech_DataAccess_WSSiebel_UpdContact_ADVWebService_UpdateContact {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_WSSiebel_UpdContact_ADVWebService_UpdateContact"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.21.1.133/ws/job.asmx")]
        public string Advantech_Myadvantech_DataAccess_CheckPointWS_Job {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_CheckPointWS_Job"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://CRMAP-GLOBAL3/eai_enu/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&" +
            "UserName=MYADVANTECH&Password=MYADVANTECH1234")]
        public string Advantech_Myadvantech_DataAccess_UpdOppty_ADVWebService_UpdOppty {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_UpdOppty_ADVWebService_UpdOppty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://member.advantech.com/membershipwebservice.asmx")]
        public string Advantech_Myadvantech_DataAccess_MemberShip_MembershipWebservice {
            get {
                return ((string)(this["Advantech_Myadvantech_DataAccess_MemberShip_MembershipWebservice"]));
            }
        }
    }
}
