'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QuotationMaster1
    
    '''<summary>
    '''UPForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPForm As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtQuoteToName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteToName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfErpId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfErpId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnPickAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPickAccount As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''hfAccountRowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAccountRowId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfQuoteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfQuoteNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''drpOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpOrg As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PLPickAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PLPickAccount As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CancelButtonAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButtonAccount As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''UPPickAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPPickAccount As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ascxPickAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ascxPickAccount As Global.EDOC.PickAccount
    
    '''<summary>
    '''lbDummyAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDummyAccount As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''MPPickAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPPickAccount As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''hfCreatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCreatedDate As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbSoldToStreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSoldToStreet As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSoldToCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSoldToCity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSoldToState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSoldToState As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSoldToZipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSoldToZipcode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSoldToCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSoldToCountry As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSoldToAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSoldToAttention As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSoldToTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSoldToTel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HFsoldtofax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFsoldtofax As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''trCreditBlockMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCreditBlockMsg As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''gvERPIDCreditBlockMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvERPIDCreditBlockMsg As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''trDSGSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDSGSO As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''upDistChannDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDistChannDiv As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''dlDistChann control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlDistChann As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbDivSalesGrpOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDivSalesGrpOffice As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtSalesDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesDivision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSalesGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesGroup As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSalesOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesOffice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSalesDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesDistrict As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSB As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbSBSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSBSAP As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtShipToName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnPickShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPickShipTo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''PLSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PLSB As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CSB As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''UPSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPSB As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PickSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickSB As Global.EDOC.PickShipToBillToSAP
    
    '''<summary>
    '''LBSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBSB As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''MPSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPSB As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''cbNewShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNewShipTo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtShipToERPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToERPID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToStreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToStreet As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToStreet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToStreet2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToCity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToState As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToZip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToCountry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToAttention As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtShipToTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToTel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HFshiptofax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFshiptofax As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tdShipto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdShipto As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''txtBillName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnPickBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPickBill As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cbNewBillTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNewBillTo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtBillID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToStreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToStreet As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToStreet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToStreet2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToCity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToState As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToZip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToCountry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToAttention As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBillToTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillToTel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HFbilltofax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFbilltofax As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tdEM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdEM As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''txtEMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnPickEM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPickEM As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtEMERPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMERPID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMStreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMStreet As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMStreet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMStreet2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMCity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMState As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMZip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMCountry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMAttention As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEMTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMTel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HFEMfax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFEMfax As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''cpeDemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeDemo As Global.AjaxControlToolkit.CollapsiblePanelExtender
    
    '''<summary>
    '''Label20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreatedBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label21 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtQuoteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtExpiredDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpiredDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalExt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalExt1 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Filteredtextboxextender6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender6 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''DDLExpiredDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLExpiredDays As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbPreparedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPreparedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPreparedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPreparedBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbOfficeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbOfficeGroup As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''Label13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''h_office control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents h_office As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''drpSalesOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSalesOffice As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbGroup As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drpGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trCurrencyRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCurrencyRow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drpCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpCurrency As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSalesEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AutoCompleteExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender4 As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''hfSalesRowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSalesRowId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LabelAlternativeSalesEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAlternativeSalesEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSalesEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesEmail1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender1 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''AutoCompleteExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender1 As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''trSalesContactNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSalesContactNum As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label1SalesContactNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1SalesContactNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDirectPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDirectPhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trCustomerContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCustomerContact As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttention As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAttentionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttentionName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ibtnPickAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnPickAttention As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''hfAttentionRowId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAttentionRowId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''PLPickAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PLPickAttention As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CancelButtonAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButtonAttention As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''UPPickAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPPickAttention As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ascxPickAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ascxPickAttention As Global.EDOC.PickAttention
    
    '''<summary>
    '''lbDummyAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDummyAttention As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''MPPickAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPPickAttention As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''trBankInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBankInfo As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBankInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trInsideSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInsideSales As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlAENCInsideSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAENCInsideSales As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trDeliveryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDeliveryDate As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDeliveryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeliveryDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbxDelDateFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxDelDateFlag As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Filteredtextboxextender5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender5 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''trExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trExempt As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''cbxIsTaxExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxIsTaxExempt As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''trShipTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trShipTerm As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dlShipTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlShipTerm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trIncoterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trIncoterm As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtInco1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInco1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DDLInco1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLInco1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtInco2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInco2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dlPaymentTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlPaymentTerm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEmployee As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label22 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drpSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drpSE2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSE2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drpSE3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSE3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trAJPEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAJPEmployee As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAJPSalesEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAJPSalesEmployee As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trRefPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRefPO As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtRefPONO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefPONO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbUploadPOFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUploadPOFile As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''updPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPO As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUploadPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadPO As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''trSourcefrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSourcefrom As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlQuoteSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuoteSource As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trCareOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCareOn As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtCareOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCareOn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trABRQuoteType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trABRQuoteType As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlABRQuoteType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlABRQuoteType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trFreightInsuSPTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFreightInsuSPTax As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTax As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Filteredtextboxextender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender4 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''LabelFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFreight As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Filteredtextboxextender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender1 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''trSpecialChargeInsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSpecialChargeInsurance As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''LabelSpecialCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSpecialCharge As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSpecialCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecialCharge As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Filteredtextboxextender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender3 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''LabelInsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelInsurance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtInsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsurance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Filteredtextboxextender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filteredtextboxextender2 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''txtQuoteDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteDesc As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Description As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SP_star1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SP_star1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtCustomId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEngineer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LabelEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEngineer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TBEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBEngineer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label_EngineerTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_EngineerTel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TBEngineerTEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBEngineerTEL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label_Warrenty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Warrenty As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWarranty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarranty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trQuoteNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuoteNote As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtQuoteNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trLowGPReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLowGPReason As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRelatedInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelatedInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trEmailGreeting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEmailGreeting As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEmailGreeting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailGreeting As Global.EDOC.NoToolBarEditor
    
    '''<summary>
    '''trSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSignature As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSignature As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ImgButtonRemoveSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgButtonRemoveSignature As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ImgButtonPickSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgButtonPickSignature As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''HFSignatureID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFSignatureID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''PLPickSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PLPickSignature As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CancelButtonSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButtonSignature As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''UPPickSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPPickSignature As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ascxPickSignature1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ascxPickSignature1 As Global.EDOC.PickSignature
    
    '''<summary>
    '''lbDummySignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDummySignature As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''MPPickSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPPickSignature As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''Hysignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hysignature As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''trSpecialTandC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSpecialTandC As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSpecialTandC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecialTandC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trRepeatedOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRepeatedOrder As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label23 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbxIsRepeatedOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxIsRepeatedOrder As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''trReVisionControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trReVisionControl As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonCreateNewRevision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCreateNewRevision As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DDLRevisionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLRevisionNumber As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ButtonMakeItActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonMakeItActive As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cbxIsActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxIsActive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ascxCustomerCreditInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ascxCustomerCreditInfo As Global.EDOC.UCCreditInfo
    
    '''<summary>
    '''tableopty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableopty As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''UP_Opty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP_Opty As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LabelOptyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOptyName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOptyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOptyName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelOptyStage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOptyStage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DDLOptyStage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLOptyStage As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ibtn_PickOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtn_PickOpty As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ButtonNewOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonNewOpty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cbx_NewOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_NewOpty As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Label24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label24 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOptyRowID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOptyRowID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PLPickOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PLPickOpty As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''CancelButtonOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButtonOpty As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''UPPickOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPPickOpty As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ascxPickopty1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ascxPickopty1 As Global.EDOC.PickSiebelOpportunity
    
    '''<summary>
    '''lbDummyOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDummyOpty As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''MPPickOpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPPickOpty As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''HFOriginalQuoteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFOriginalQuoteID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HFAKRQuoteListPriceOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFAKRQuoteListPriceOnly As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirm As Global.System.Web.UI.WebControls.Button
End Class
