
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ACN_EQ_PSM
{

    public int Id { get; set; }

    public string Sector { get; set; }

    public string PG { get; set; }

    public string ProductDivision { get; set; }

    public string PSM { get; set; }

    public Nullable<int> Level { get; set; }

}

}
