
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class AJP_ConfiguratorTerms
{

    public string QuoteID { get; set; }

    public string HW_COMUSB { get; set; }

    public string HW_Storage { get; set; }

    public string HW_SATA { get; set; }

    public string HW_Disk_Division { get; set; }

    public string HW_Cable { get; set; }

    public string HW_BIOS { get; set; }

    public string HW_OS_License { get; set; }

    public string HW_OS_Activation { get; set; }

    public string HW_Others { get; set; }

    public string SW_OS_Installation { get; set; }

    public string SW_Username { get; set; }

    public string SW_OS_Timezone { get; set; }

    public string SW_OS_Input { get; set; }

    public string SW_IP_Settings { get; set; }

    public string SW_Settings { get; set; }

    public string SW_Others { get; set; }

    public string FINAL_HWSummary { get; set; }

    public string FINAL_SWSummary { get; set; }

    public string IFS_SOP { get; set; }

}

}
