
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BB_CREDITCARD_ORDER
{

    public int ID { get; set; }

    public string ORDER_NO { get; set; }

    public string CARD_NO { get; set; }

    public string CARD_TYPE { get; set; }

    public string TRANSACTION_TYPE { get; set; }

    public string STATUS { get; set; }

    public string MESSAGE { get; set; }

    public string TRANSACTION_ID { get; set; }

    public string AUTH_CODE { get; set; }

    public Nullable<decimal> TOTAL_AUTH_AMOUNT { get; set; }

    public Nullable<System.DateTime> CREATED_DATE { get; set; }

    public string CREATED_By { get; set; }

}

}
