
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class cart_DETAIL_V2
{

    public int ID { get; set; }

    public string Cart_Id { get; set; }

    public Nullable<int> Line_No { get; set; }

    public string Part_No { get; set; }

    public string Description { get; set; }

    public Nullable<int> Qty { get; set; }

    public Nullable<decimal> List_Price { get; set; }

    public Nullable<decimal> Unit_Price { get; set; }

    public Nullable<decimal> Itp { get; set; }

    public Nullable<decimal> RecyclingFee { get; set; }

    public string Delivery_Plant { get; set; }

    public string Category { get; set; }

    public string @class { get; set; }

    public Nullable<int> rohs { get; set; }

    public Nullable<int> Ew_Flag { get; set; }

    public Nullable<System.DateTime> req_date { get; set; }

    public Nullable<System.DateTime> due_date { get; set; }

    public Nullable<int> SatisfyFlag { get; set; }

    public Nullable<int> CanbeConfirmed { get; set; }

    public string CustMaterial { get; set; }

    public Nullable<int> inventory { get; set; }

    public Nullable<int> otype { get; set; }

    public string Model_No { get; set; }

    public string QUOTE_ID { get; set; }

    public Nullable<decimal> oUnit_Price { get; set; }

    public Nullable<int> higherLevel { get; set; }

    public string PRODUCT_FAMILY { get; set; }

}

}
