//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckPointDBEntities1 : DbContext
    {
        public CheckPointDBEntities1()
            : base("name=CheckPointDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SO_HEADER> SO_HEADER { get; set; }
        public virtual DbSet<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual DbSet<SO_PARTNERFUNC> SO_PARTNERFUNC { get; set; }
        public virtual DbSet<Ship_to_Information> Ship_to_Information { get; set; }
    }
}
