
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EQPARTNER
{

    public string QUOTEID { get; set; }

    public string ROWID { get; set; }

    public string ERPID { get; set; }

    public string NAME { get; set; }

    public string ADDRESS { get; set; }

    public string TYPE { get; set; }

    public string ATTENTION { get; set; }

    public string TEL { get; set; }

    public string MOBILE { get; set; }

    public string ZIPCODE { get; set; }

    public string COUNTRY { get; set; }

    public string CITY { get; set; }

    public string STREET { get; set; }

    public string STATE { get; set; }

    public string DISTRICT { get; set; }

    public string STREET2 { get; set; }

    public string FAX { get; set; }

}

}
