//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedWarrantyPartNo_V2
    {
        public int ID { get; set; }
        public string EW_PartNO { get; set; }
        public Nullable<int> EW_Month { get; set; }
        public Nullable<decimal> EW_Rate { get; set; }
        public string Plant { get; set; }
        public Nullable<int> SeqNO { get; set; }
        public string SalesGroup { get; set; }
    }
}
