
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class HubConfiguredResult
{

    public string ID { get; set; }

    public string Source { get; set; }

    public int ParentLineNo { get; set; }

    public Nullable<int> Result { get; set; }

    public string RootID { get; set; }

    public string SelectedItems { get; set; }

    public string CompanyID { get; set; }

    public string Currency { get; set; }

    public string ReConfigData { get; set; }

    public Nullable<System.DateTime> CreatedTime { get; set; }

}

}
