//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAdminEntity : DbContext
    {
        public MyAdminEntity()
            : base("name=MyAdminEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SA_BAPIADDR1> SA_BAPIADDR1 { get; set; }
        public DbSet<SA_BAPIADDR2> SA_BAPIADDR2 { get; set; }
        public DbSet<SA_FKNBK> SA_FKNBK { get; set; }
        public DbSet<SA_FKNVI> SA_FKNVI { get; set; }
        public DbSet<SA_KNA1> SA_KNA1 { get; set; }
        public DbSet<SA_KNB1> SA_KNB1 { get; set; }
        public DbSet<SA_KNVV> SA_KNVV { get; set; }
        public DbSet<SA_Files> SA_Files { get; set; }
        public DbSet<SA_Proposal> SA_Proposal { get; set; }
        public DbSet<SA_APPLICATION> SA_APPLICATION { get; set; }
        public DbSet<SA_APPLICATION2COMPANY> SA_APPLICATION2COMPANY { get; set; }
    }
}
