
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Quotation_Approval_Expiration
{

    public int ID { get; set; }

    public string QuoteID { get; set; }

    public string Approver { get; set; }

    public Nullable<double> GPlever { get; set; }

    public Nullable<int> ApprovalLevel { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string MobileApproveYes { get; set; }

    public string MobileApproveNo { get; set; }

    public Nullable<System.DateTime> ApprovalDate { get; set; }

    public string ApprovalFrom { get; set; }

    public string ApprovalFlowType { get; set; }

}

}
