
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class quoteSiebelQuote
{

    public string quoteId { get; set; }

    public string siebelQuoteId { get; set; }

    public string processId { get; set; }

    public int ID { get; set; }

}

}
