
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class QuotationDetail
{

    public int id { get; set; }

    public string quoteId { get; set; }

    public Nullable<int> line_No { get; set; }

    public string partNo { get; set; }

    public string description { get; set; }

    public Nullable<int> qty { get; set; }

    public Nullable<decimal> listPrice { get; set; }

    public Nullable<decimal> unitPrice { get; set; }

    public Nullable<decimal> newUnitPrice { get; set; }

    public Nullable<decimal> itp { get; set; }

    public Nullable<decimal> newItp { get; set; }

    public Nullable<decimal> RecyclingFee { get; set; }

    public string deliveryPlant { get; set; }

    public string category { get; set; }

    public string classABC { get; set; }

    public Nullable<int> rohs { get; set; }

    public Nullable<int> ewFlag { get; set; }

    public Nullable<System.DateTime> reqDate { get; set; }

    public Nullable<System.DateTime> dueDate { get; set; }

    public Nullable<int> satisfyFlag { get; set; }

    public Nullable<int> canBeConfirmed { get; set; }

    public string custMaterial { get; set; }

    public Nullable<int> inventory { get; set; }

    public Nullable<int> oType { get; set; }

    public string modelNo { get; set; }

    public string sprNo { get; set; }

    public Nullable<int> HigherLevel { get; set; }

    public string DMF_Flag { get; set; }

    public Nullable<int> ItemType { get; set; }

    public string VirtualPartNo { get; set; }

    public string DELIVERYGROUP { get; set; }

    public string ShipPoint { get; set; }

    public string StorageLoc { get; set; }

    public string RECFIGID { get; set; }

    public string DisplayUnitPrice { get; set; }

    public string DisplayQty { get; set; }

    public string DisplayLineNo { get; set; }

    public Nullable<int> SequenceNo { get; set; }

    public Nullable<int> NCNR { get; set; }

}

}
