//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_KNA1
    {
        public int ID { get; set; }
        public int HeadID { get; set; }
        public string Abrvw { get; set; }
        public string Adrnr { get; set; }
        public string Alc { get; set; }
        public string Anred { get; set; }
        public string Aufsd { get; set; }
        public string Bahne { get; set; }
        public string Bahns { get; set; }
        public string Bbbnr { get; set; }
        public string Bbsnr { get; set; }
        public string Begru { get; set; }
        public string Bran1 { get; set; }
        public string Bran2 { get; set; }
        public string Bran3 { get; set; }
        public string Bran4 { get; set; }
        public string Bran5 { get; set; }
        public string Brsch { get; set; }
        public string Bubkz { get; set; }
        public string Cassd { get; set; }
        public string Ccc01 { get; set; }
        public string Ccc02 { get; set; }
        public string Ccc03 { get; set; }
        public string Ccc04 { get; set; }
        public string Cfopc { get; set; }
        public string Cityc { get; set; }
        public string Civve { get; set; }
        public string Confs { get; set; }
        public string Counc { get; set; }
        public string Datlt { get; set; }
        public string Dear1 { get; set; }
        public string Dear2 { get; set; }
        public string Dear3 { get; set; }
        public string Dear4 { get; set; }
        public string Dear5 { get; set; }
        public string Dear6 { get; set; }
        public string Dtams { get; set; }
        public string Dtaws { get; set; }
        public string Duefl { get; set; }
        public string Ekont { get; set; }
        public string Erdat { get; set; }
        public string Ernam { get; set; }
        public string Etikg { get; set; }
        public string Exabl { get; set; }
        public string Faksd { get; set; }
        public string Fiskn { get; set; }
        public string Fityp { get; set; }
        public string Gform { get; set; }
        public string Hzuor { get; set; }
        public string Inspatdebi { get; set; }
        public string Inspbydebi { get; set; }
        public string J_1kfrepre { get; set; }
        public string J_1kftbus { get; set; }
        public string J_1kftind { get; set; }
        public string Jmjah { get; set; }
        public string Jmzah { get; set; }
        public string Katr1 { get; set; }
        public string Katr10 { get; set; }
        public string Katr2 { get; set; }
        public string Katr3 { get; set; }
        public string Katr4 { get; set; }
        public string Katr5 { get; set; }
        public string Katr6 { get; set; }
        public string Katr7 { get; set; }
        public string Katr8 { get; set; }
        public string Katr9 { get; set; }
        public string Kdkg1 { get; set; }
        public string Kdkg2 { get; set; }
        public string Kdkg3 { get; set; }
        public string Kdkg4 { get; set; }
        public string Kdkg5 { get; set; }
        public string Knazk { get; set; }
        public string Knrza { get; set; }
        public string Knurl { get; set; }
        public string Konzs { get; set; }
        public string Ktocd { get; set; }
        public string Ktokd { get; set; }
        public string Kukla { get; set; }
        public string Kunnr { get; set; }
        public string Land1 { get; set; }
        public string Lifnr { get; set; }
        public string Lifsd { get; set; }
        public string Locco { get; set; }
        public string Loevm { get; set; }
        public string Lzone { get; set; }
        public string Mandt { get; set; }
        public string Mcod1 { get; set; }
        public string Mcod2 { get; set; }
        public string Mcod3 { get; set; }
        public string Milve { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string Niels { get; set; }
        public string Nodel { get; set; }
        public string Ort01 { get; set; }
        public string Ort02 { get; set; }
        public string Periv { get; set; }
        public string Pfach { get; set; }
        public string Pfort { get; set; }
        public string Pmt_Office { get; set; }
        public string Psofg { get; set; }
        public string Psohs { get; set; }
        public string Psois { get; set; }
        public string Pson1 { get; set; }
        public string Pson2 { get; set; }
        public string Pson3 { get; set; }
        public string Psoo1 { get; set; }
        public string Psoo2 { get; set; }
        public string Psoo3 { get; set; }
        public string Psoo4 { get; set; }
        public string Psoo5 { get; set; }
        public string Psost { get; set; }
        public string Psotl { get; set; }
        public string Psovn { get; set; }
        public string Pstl2 { get; set; }
        public string Pstlz { get; set; }
        public string Regio { get; set; }
        public string Rpmkr { get; set; }
        public string Sortl { get; set; }
        public string Sperr { get; set; }
        public string Sperz { get; set; }
        public string Spras { get; set; }
        public string Stcd1 { get; set; }
        public string Stcd2 { get; set; }
        public string Stcd3 { get; set; }
        public string Stcd4 { get; set; }
        public string Stcd5 { get; set; }
        public string Stcdt { get; set; }
        public string Stceg { get; set; }
        public string Stkza { get; set; }
        public string Stkzn { get; set; }
        public string Stkzu { get; set; }
        public string Stras { get; set; }
        public string Telbx { get; set; }
        public string Telf1 { get; set; }
        public string Telf2 { get; set; }
        public string Telfx { get; set; }
        public string Teltx { get; set; }
        public string Telx1 { get; set; }
        public string Txjcd { get; set; }
        public string Txlw1 { get; set; }
        public string Txlw2 { get; set; }
        public string Umjah { get; set; }
        public string Umsa1 { get; set; }
        public string Umsat { get; set; }
        public string Updat { get; set; }
        public string Uptim { get; set; }
        public string Uwaer { get; set; }
        public string Vbund { get; set; }
        public string Vso_R_Dpoint { get; set; }
        public string Vso_R_I_No_Lyr { get; set; }
        public string Vso_R_Load_Pref { get; set; }
        public string Vso_R_Matpal { get; set; }
        public string Vso_R_One_Mat { get; set; }
        public string Vso_R_One_Sort { get; set; }
        public string Vso_R_Pal_Ul { get; set; }
        public string Vso_R_Palhgt { get; set; }
        public string Vso_R_Pk_Mat { get; set; }
        public string Vso_R_Uld_Side { get; set; }
        public string Werks { get; set; }
        public string Xcpdk { get; set; }
        public string Xicms { get; set; }
        public string Xknza { get; set; }
        public string Xsubt { get; set; }
        public string Xxipi { get; set; }
        public string Xzemp { get; set; }
    
        public virtual SA_APPLICATION2COMPANY SA_APPLICATION2COMPANY { get; set; }
    }
}
