
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class SAP_PRODUCT_ABC
{

    public string PART_NO { get; set; }

    public string PLANT { get; set; }

    public string ABC_INDICATOR { get; set; }

    public Nullable<int> PLANNED_DEL_TIME { get; set; }

    public Nullable<int> GP_PROCESSING_TIME { get; set; }

    public Nullable<int> IN_HOUSE_PRODUCTION { get; set; }

    public string ProfitCenter { get; set; }

    public string Ctrl_Code { get; set; }

    public Nullable<double> safety_stock { get; set; }

    public Nullable<double> min_safety_stock { get; set; }

    public Nullable<decimal> service_level { get; set; }

    public Nullable<decimal> MIN_LOT_SIZE { get; set; }

    public long ID { get; set; }

    public string FREIGHT_METHOD { get; set; }

    public string COUNTRY_ORIGIN { get; set; }

}

}
