
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class SiebelActive
{

    public int ID { get; set; }

    public string ActiveSource { get; set; }

    public string ActiveType { get; set; }

    public string Status { get; set; }

    public string QuoteID { get; set; }

    public string OrderID { get; set; }

    public string OptyID { get; set; }

    public string OptyName { get; set; }

    public string OptyStage { get; set; }

    public string OptyOwnerEmail { get; set; }

    public string FailedLog { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreateBy { get; set; }

    public Nullable<System.DateTime> LastUpdatedDate { get; set; }

    public string LastUpdatedBy { get; set; }

    public string ProcessID { get; set; }

    public string Subject { get; set; }

    public string Greeting { get; set; }

    public string SendToMails { get; set; }

    public string ContactRowId { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public string WSParameters { get; set; }

}

}
