
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class SIEBEL_CONTACT
{

    public string ROW_ID { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string WorkPhone { get; set; }

    public string CellPhone { get; set; }

    public string FaxNumber { get; set; }

    public string JOB_FUNCTION { get; set; }

    public string PAR_ROW_ID { get; set; }

    public string ERPID { get; set; }

    public string PriOrgId { get; set; }

    public string OrgID { get; set; }

    public string OwnerId { get; set; }

    public string CanSeeOrder { get; set; }

    public string Password { get; set; }

    public string Sales_Rep { get; set; }

    public string NeverEmail { get; set; }

    public string NeverCall { get; set; }

    public string NeverFax { get; set; }

    public string NeverMail { get; set; }

    public string JOB_TITLE { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public string COMMENTS { get; set; }

    public string ACCOUNT_ROW_ID { get; set; }

    public string ACCOUNT { get; set; }

    public string ACCOUNT_TYPE { get; set; }

    public string ACCOUNT_STATUS { get; set; }

    public string COUNTRY { get; set; }

    public string Salutation { get; set; }

    public string EMPLOYEE_FLAG { get; set; }

    public string ACTIVE_FLAG { get; set; }

    public string USER_TYPE { get; set; }

    public string REG_SOURCE { get; set; }

    public Nullable<System.DateTime> CREATED { get; set; }

    public Nullable<System.DateTime> LAST_UPDATED { get; set; }

    public string PRIMARY_FLAG { get; set; }

    public string GDPR_STATUS { get; set; }

}

}
