//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_DETAIL
    {
        public string SO { get; set; }
        public string PART_Dlv { get; set; }
        public string HIGHER_LEVEL { get; set; }
        public string LINE_NO { get; set; }
        public string DELIVERY_GROUP { get; set; }
        public string PLANT { get; set; }
        public string MATERIAL { get; set; }
        public string CUST_MATERIAL { get; set; }
        public string DMF_FLAG { get; set; }
        public string QTY { get; set; }
        public string REQ_DATE { get; set; }
        public string PRICE { get; set; }
        public string CURRENCY { get; set; }
        public string ShipPoint { get; set; }
        public string StorageLoc { get; set; }
        public string Description { get; set; }
        public string ItCa { get; set; }
        public string POLineNo { get; set; }
    }
}
