//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advantech.Myadvantech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_HEADER
    {
        public string SO { get; set; }
        public string ORDER_TYPE { get; set; }
        public string SALES_ORG { get; set; }
        public string DIST_CHAN { get; set; }
        public string DIVISION { get; set; }
        public string SalesGroup { get; set; }
        public string SalesOffice { get; set; }
        public string INCO1 { get; set; }
        public string INCO2 { get; set; }
        public string SHIPTO_COUNTRY { get; set; }
        public string TAX_CLASS { get; set; }
        public string TRIANGULAR_INDICATOR { get; set; }
        public string REQUIRE_DATE { get; set; }
        public string SHIP_CONDITION { get; set; }
        public string CUST_PO_NO { get; set; }
        public string SHIP_CUST_PO_NO { get; set; }
        public string PO_DATE { get; set; }
        public string PARTIAL_SHIPMENT { get; set; }
        public string EARLY_SHIP { get; set; }
        public string TAXDEL_CTY { get; set; }
        public string TAXDES_CTY { get; set; }
        public string DEST_TYPE { get; set; }
        public string PAYTERM { get; set; }
        public string DOC_DATE { get; set; }
        public string DOC_DATESpecified { get; set; }
        public string DISTRICT { get; set; }
        public string Ref_Doc { get; set; }
        public string VERSION { get; set; }
        public string Currency { get; set; }
    }
}
