
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Advantech.Myadvantech.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class WorkFlowApproval
{

    public string UID { get; set; }

    public string TypeID { get; set; }

    public string Type { get; set; }

    public string Approver { get; set; }

    public string ApproverType { get; set; }

    public decimal LevelNum { get; set; }

    public int Status { get; set; }

    public Nullable<int> IsSendSuccessfully { get; set; }

    public string MobileYes { get; set; }

    public string MobileNo { get; set; }

    public string RejectedBy { get; set; }

    public Nullable<System.DateTime> RejectedDate { get; set; }

    public string RejectReason { get; set; }

    public string ApprovedBy { get; set; }

    public Nullable<System.DateTime> ApprovedDate { get; set; }

    public string ApprovedReason { get; set; }

    public string Mailbody { get; set; }

    public string WorkFlowID { get; set; }

    public string Url { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> LastUpdatedDate { get; set; }

    public Nullable<int> ViewGP { get; set; }

    public string FinalMailBody { get; set; }

}

}
