//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;

[assembly: InternalsVisibleTo("Advantech.Myadvantech.Business")]
namespace Advantech.Myadvantech.DataAccess
{
    public class DocumentBase
    {
        public virtual String ID
        {
            get;
            set;
        }

        public virtual List<Product> LineItems
        {
            get;
            set;
        }
        public virtual string  OrgID
        {
            get;
            set;
        }
        public virtual string Currency
        {
            get;
            set;
        }

        public virtual string Version
        {
            get;
            set;
        }


    }
}
