'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BRAOnlineQuoteTemplate
    
    '''<summary>
    '''LabelQuoteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelQuoteID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelQuoteRevisionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelQuoteRevisionNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''quoteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quoteDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''expiredDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents expiredDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Table_SoldTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_SoldTo As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblSoldtoERPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoldtoERPID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Cell_SoldTo_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_SoldTo_Company As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_SoldTo_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_SoldTo_Address As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_SoldTo_Tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_SoldTo_Tel As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_SoldTo_Attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_SoldTo_Attention As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Table_ShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_ShipTo As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblShipToERPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShipToERPID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Cell_ShipTo_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_ShipTo_Company As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_ShipTo_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_ShipTo_Address As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_ShipTo_Tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_ShipTo_Tel As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_ShipTo_Attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_ShipTo_Attention As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''tdBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBill As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''Table_BillTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_BillTo As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblBillToERPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBillToERPID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Cell_BillTo_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_BillTo_Company As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_BillTo_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_BillTo_Address As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_BillTo_Tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_BillTo_Tel As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''Cell_BillTo_Attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cell_BillTo_Attention As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblSalesPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSalesPerson As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LbTotal_BX41_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbTotal_BX41_1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LbTotal_BX41_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbTotal_BX41_2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LbTotal_BX95_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbTotal_BX95_1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LbTotal_FK00_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbTotal_FK00_1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelTotal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTotal5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LbTotal_BK10_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbTotal_BK10_1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelTotal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTotal7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LbTotal_BX40_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbTotal_BX40_1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbQuotationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbQuotationType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbIncoterm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbIncoterm1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPayment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbDeliveryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDeliveryDate As Global.System.Web.UI.WebControls.Label
End Class
