'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JPAOnlineQuoteTemplateV2
    
    '''<summary>
    '''SoldToCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SoldToCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelQuoteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelQuoteID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomerOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerOffice As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''quoteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quoteDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomerContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerContact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''expiredDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents expiredDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerPhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SaleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaleName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Creator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Creator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RepeaterDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeaterDetail As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''LitNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitNotes As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''PaymentTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentTerm As Global.System.Web.UI.WebControls.Label
End Class
