'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QuotationViewOption
    
    '''<summary>
    '''UP_QuotationViewOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP_QuotationViewOption As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''HFQuoteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFQuoteID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RadioButtonList_FormatOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList_FormatOptions As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rbtnIsVirtualItmeOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnIsVirtualItmeOnly As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RadioButtonList_ATWFormatOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList_ATWFormatOptions As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''RadioButtonList_AJPFormatOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList_AJPFormatOptions As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbNCNR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNCNR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbChangeQuoteTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChangeQuoteTitle As Global.System.Web.UI.WebControls.CheckBox
End Class
