'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderAddress

    '''<summary>
    '''upShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upShipTo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''trerpid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trerpid As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnShipPick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShipPick As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''trErpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trErpName As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtShipToName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShipToStreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToStreet As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShipToStreet2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToStreet2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShipToCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShipToState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShipToZipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToZipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShipToCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAttention As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtShipToAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToAttention As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShipToTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipToTel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lk_shipto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_shipto As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MP_shipto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MP_shipto As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''PL_shipto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PL_shipto As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''up_shipto_c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up_shipto_c As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ucShipToUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucShipToUS As Global.EDOC.USAOnlineShipBillTo
End Class
