'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderInfo1

    '''<summary>
    '''lbPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSO As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lbSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbOrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOrderDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPayTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPayTerm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbPlacedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPlacedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbIncoterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbIncoterm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFreight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbSalesRepTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSalesRepTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbSalesRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSalesRep As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trPartial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPartial As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbisPartial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbisPartial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbOrderNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOrderNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbQuoteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbQuoteNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trReqdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trReqdate As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbReqdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbReqdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelShipCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelShipCondition As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbShipCond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShipCond As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trSalesNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSalesNote As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSalesNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSalesNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trEUOPN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEUOPN As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbOPNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOPNote As Global.System.Web.UI.WebControls.Label
End Class
