'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class soldtoshipto

    '''<summary>
    '''litsoldto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litsoldto As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litshipto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litshipto As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litsoldtocompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litsoldtocompany As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litshiptocompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litshiptocompany As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litsoldtoaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litsoldtoaddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litshiptoaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litshiptoaddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litsoldtotel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litsoldtotel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litshiptoaddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litshiptoaddress2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litshiptotel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litshiptotel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litsoldtoattention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litsoldtoattention As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litshiptoattention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litshiptoattention As Global.System.Web.UI.WebControls.Literal
End Class
