//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Advantech.Myadvantech.DataAccess.WSSiebel_AddQuote {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ADVWebService-AddQuote", Namespace="http://siebel.com/CustomUI")]
    public partial class ADVWebServiceAddQuote : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddQuoteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ADVWebServiceAddQuote() {
            this.Url = global::Advantech.Myadvantech.DataAccess.Properties.Settings.Default.Advantech_Myadvantech_DataAccess_WSSiebel_AddQuote_ADVWebService_AddQuote;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddQuoteCompletedEventHandler AddQuoteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/http://siebel.com/CustomUI:AddQuote", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddQuote_Output", Namespace="http://siebel.com/CustomUI")]
        public AddQuote_Output AddQuote([System.Xml.Serialization.XmlElementAttribute(Namespace="http://siebel.com/CustomUI")] AddQuote_Input AddQuote_Input) {
            object[] results = this.Invoke("AddQuote", new object[] {
                        AddQuote_Input});
            return ((AddQuote_Output)(results[0]));
        }
        
        /// <remarks/>
        public void AddQuoteAsync(AddQuote_Input AddQuote_Input) {
            this.AddQuoteAsync(AddQuote_Input, null);
        }
        
        /// <remarks/>
        public void AddQuoteAsync(AddQuote_Input AddQuote_Input, object userState) {
            if ((this.AddQuoteOperationCompleted == null)) {
                this.AddQuoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddQuoteOperationCompleted);
            }
            this.InvokeAsync("AddQuote", new object[] {
                        AddQuote_Input}, this.AddQuoteOperationCompleted, userState);
        }
        
        private void OnAddQuoteOperationCompleted(object arg) {
            if ((this.AddQuoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddQuoteCompleted(this, new AddQuoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class AddQuote_Input {
        
        private QUOTE qUOTEField;
        
        private string sOURCEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.siebel.com/xml/ADVQuoteIO")]
        public QUOTE QUOTE {
            get {
                return this.qUOTEField;
            }
            set {
                this.qUOTEField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE {
            get {
                return this.sOURCEField;
            }
            set {
                this.sOURCEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVQuoteIO")]
    public partial class QUOTE {
        
        private string aCCOUNT_IDField;
        
        private string cOMMENTSField;
        
        private string dUE_DATEField;
        
        private string nAMEField;
        
        private string oPPORTUNITY_IDField;
        
        private string cURRENCY_CODEField;
        
        private ORGANIZATION[] oRGANIZATIONField;
        
        private POSITION[] pOSITIONField;
        
        private QUOTE_ITEM[] qUOTE_ITEMField;
        
        /// <remarks/>
        public string ACCOUNT_ID {
            get {
                return this.aCCOUNT_IDField;
            }
            set {
                this.aCCOUNT_IDField = value;
            }
        }
        
        /// <remarks/>
        public string COMMENTS {
            get {
                return this.cOMMENTSField;
            }
            set {
                this.cOMMENTSField = value;
            }
        }
        
        /// <remarks/>
        public string DUE_DATE {
            get {
                return this.dUE_DATEField;
            }
            set {
                this.dUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string OPPORTUNITY_ID {
            get {
                return this.oPPORTUNITY_IDField;
            }
            set {
                this.oPPORTUNITY_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CURRENCY_CODE {
            get {
                return this.cURRENCY_CODEField;
            }
            set {
                this.cURRENCY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORGANIZATION")]
        public ORGANIZATION[] ORGANIZATION {
            get {
                return this.oRGANIZATIONField;
            }
            set {
                this.oRGANIZATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSITION")]
        public POSITION[] POSITION {
            get {
                return this.pOSITIONField;
            }
            set {
                this.pOSITIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QUOTE_ITEM")]
        public QUOTE_ITEM[] QUOTE_ITEM {
            get {
                return this.qUOTE_ITEMField;
            }
            set {
                this.qUOTE_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVQuoteIO")]
    public partial class ORGANIZATION {
        
        private string nAMEField;
        
        private string iS_PRIMARYField;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IS_PRIMARY {
            get {
                return this.iS_PRIMARYField;
            }
            set {
                this.iS_PRIMARYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVQuoteIO")]
    public partial class QUOTE_ITEM {
        
        private string pRODUCT_NAMEField;
        
        private string pRODUCT_QUANTITYField;
        
        private string dELIVERY_DATEField;
        
        private string dISCOUNT_PRICEField;
        
        /// <remarks/>
        public string PRODUCT_NAME {
            get {
                return this.pRODUCT_NAMEField;
            }
            set {
                this.pRODUCT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_QUANTITY {
            get {
                return this.pRODUCT_QUANTITYField;
            }
            set {
                this.pRODUCT_QUANTITYField = value;
            }
        }
        
        /// <remarks/>
        public string DELIVERY_DATE {
            get {
                return this.dELIVERY_DATEField;
            }
            set {
                this.dELIVERY_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string DISCOUNT_PRICE {
            get {
                return this.dISCOUNT_PRICEField;
            }
            set {
                this.dISCOUNT_PRICEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/ADVQuoteIO")]
    public partial class POSITION {
        
        private string nAMEField;
        
        private string iS_PRIMARYField;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IS_PRIMARY {
            get {
                return this.iS_PRIMARYField;
            }
            set {
                this.iS_PRIMARYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class AddQuote_Output {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string rOW_IDField;
        
        private string sTATUSField;
        
        /// <remarks/>
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ROW_ID {
            get {
                return this.rOW_IDField;
            }
            set {
                this.rOW_IDField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AddQuoteCompletedEventHandler(object sender, AddQuoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddQuoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddQuoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddQuote_Output Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddQuote_Output)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591