//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Advantech.Myadvantech.DataAccess.WSSiebel_New {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSiebelSoap", Namespace="http://tempuri.org/")]
    public partial class WSSiebel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPositionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSRInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContactListunderAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContactPrivilegeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountPrimarySalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountContactAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSRUnderAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActivitiesUnderSROperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSSiebel() {
            this.Url = global::Advantech.Myadvantech.DataAccess.Properties.Settings.Default.Advantech_Myadvantech_DataAccess_WSSiebel_New_WSSiebel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckContactCompletedEventHandler CheckContactCompleted;
        
        /// <remarks/>
        public event CheckEmployeeCompletedEventHandler CheckEmployeeCompleted;
        
        /// <remarks/>
        public event CheckPositionCompletedEventHandler CheckPositionCompleted;
        
        /// <remarks/>
        public event GetSRInformationCompletedEventHandler GetSRInformationCompleted;
        
        /// <remarks/>
        public event CheckProductCompletedEventHandler CheckProductCompleted;
        
        /// <remarks/>
        public event GetContactListunderAccountCompletedEventHandler GetContactListunderAccountCompleted;
        
        /// <remarks/>
        public event GetContactPrivilegeCompletedEventHandler GetContactPrivilegeCompleted;
        
        /// <remarks/>
        public event GetAccountPrimarySalesCompletedEventHandler GetAccountPrimarySalesCompleted;
        
        /// <remarks/>
        public event GetAccountContactAdminCompletedEventHandler GetAccountContactAdminCompleted;
        
        /// <remarks/>
        public event GetSRUnderAccountCompletedEventHandler GetSRUnderAccountCompleted;
        
        /// <remarks/>
        public event GetActivitiesUnderSRCompletedEventHandler GetActivitiesUnderSRCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT CheckContact(string LoginID, string ContactEmail) {
            object[] results = this.Invoke("CheckContact", new object[] {
                        LoginID,
                        ContactEmail});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void CheckContactAsync(string LoginID, string ContactEmail) {
            this.CheckContactAsync(LoginID, ContactEmail, null);
        }
        
        /// <remarks/>
        public void CheckContactAsync(string LoginID, string ContactEmail, object userState) {
            if ((this.CheckContactOperationCompleted == null)) {
                this.CheckContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckContactOperationCompleted);
            }
            this.InvokeAsync("CheckContact", new object[] {
                        LoginID,
                        ContactEmail}, this.CheckContactOperationCompleted, userState);
        }
        
        private void OnCheckContactOperationCompleted(object arg) {
            if ((this.CheckContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckContactCompleted(this, new CheckContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT CheckEmployee(string LoginID, string EmpEmail) {
            object[] results = this.Invoke("CheckEmployee", new object[] {
                        LoginID,
                        EmpEmail});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void CheckEmployeeAsync(string LoginID, string EmpEmail) {
            this.CheckEmployeeAsync(LoginID, EmpEmail, null);
        }
        
        /// <remarks/>
        public void CheckEmployeeAsync(string LoginID, string EmpEmail, object userState) {
            if ((this.CheckEmployeeOperationCompleted == null)) {
                this.CheckEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckEmployeeOperationCompleted);
            }
            this.InvokeAsync("CheckEmployee", new object[] {
                        LoginID,
                        EmpEmail}, this.CheckEmployeeOperationCompleted, userState);
        }
        
        private void OnCheckEmployeeOperationCompleted(object arg) {
            if ((this.CheckEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckEmployeeCompleted(this, new CheckEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckPosition", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT CheckPosition(string LoginID, string Position) {
            object[] results = this.Invoke("CheckPosition", new object[] {
                        LoginID,
                        Position});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPositionAsync(string LoginID, string Position) {
            this.CheckPositionAsync(LoginID, Position, null);
        }
        
        /// <remarks/>
        public void CheckPositionAsync(string LoginID, string Position, object userState) {
            if ((this.CheckPositionOperationCompleted == null)) {
                this.CheckPositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPositionOperationCompleted);
            }
            this.InvokeAsync("CheckPosition", new object[] {
                        LoginID,
                        Position}, this.CheckPositionOperationCompleted, userState);
        }
        
        private void OnCheckPositionOperationCompleted(object arg) {
            if ((this.CheckPositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPositionCompleted(this, new CheckPositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSRInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT GetSRInformation(string LoginID, string SRID, string Type) {
            object[] results = this.Invoke("GetSRInformation", new object[] {
                        LoginID,
                        SRID,
                        Type});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetSRInformationAsync(string LoginID, string SRID, string Type) {
            this.GetSRInformationAsync(LoginID, SRID, Type, null);
        }
        
        /// <remarks/>
        public void GetSRInformationAsync(string LoginID, string SRID, string Type, object userState) {
            if ((this.GetSRInformationOperationCompleted == null)) {
                this.GetSRInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSRInformationOperationCompleted);
            }
            this.InvokeAsync("GetSRInformation", new object[] {
                        LoginID,
                        SRID,
                        Type}, this.GetSRInformationOperationCompleted, userState);
        }
        
        private void OnGetSRInformationOperationCompleted(object arg) {
            if ((this.GetSRInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSRInformationCompleted(this, new GetSRInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT CheckProduct(string LoginID, string Product) {
            object[] results = this.Invoke("CheckProduct", new object[] {
                        LoginID,
                        Product});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void CheckProductAsync(string LoginID, string Product) {
            this.CheckProductAsync(LoginID, Product, null);
        }
        
        /// <remarks/>
        public void CheckProductAsync(string LoginID, string Product, object userState) {
            if ((this.CheckProductOperationCompleted == null)) {
                this.CheckProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckProductOperationCompleted);
            }
            this.InvokeAsync("CheckProduct", new object[] {
                        LoginID,
                        Product}, this.CheckProductOperationCompleted, userState);
        }
        
        private void OnCheckProductOperationCompleted(object arg) {
            if ((this.CheckProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckProductCompleted(this, new CheckProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetContactListunderAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT GetContactListunderAccount(string LoginID, string AccountId) {
            object[] results = this.Invoke("GetContactListunderAccount", new object[] {
                        LoginID,
                        AccountId});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetContactListunderAccountAsync(string LoginID, string AccountId) {
            this.GetContactListunderAccountAsync(LoginID, AccountId, null);
        }
        
        /// <remarks/>
        public void GetContactListunderAccountAsync(string LoginID, string AccountId, object userState) {
            if ((this.GetContactListunderAccountOperationCompleted == null)) {
                this.GetContactListunderAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactListunderAccountOperationCompleted);
            }
            this.InvokeAsync("GetContactListunderAccount", new object[] {
                        LoginID,
                        AccountId}, this.GetContactListunderAccountOperationCompleted, userState);
        }
        
        private void OnGetContactListunderAccountOperationCompleted(object arg) {
            if ((this.GetContactListunderAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContactListunderAccountCompleted(this, new GetContactListunderAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetContactPrivilege", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT GetContactPrivilege(string LoginID, string cEmail) {
            object[] results = this.Invoke("GetContactPrivilege", new object[] {
                        LoginID,
                        cEmail});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetContactPrivilegeAsync(string LoginID, string cEmail) {
            this.GetContactPrivilegeAsync(LoginID, cEmail, null);
        }
        
        /// <remarks/>
        public void GetContactPrivilegeAsync(string LoginID, string cEmail, object userState) {
            if ((this.GetContactPrivilegeOperationCompleted == null)) {
                this.GetContactPrivilegeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactPrivilegeOperationCompleted);
            }
            this.InvokeAsync("GetContactPrivilege", new object[] {
                        LoginID,
                        cEmail}, this.GetContactPrivilegeOperationCompleted, userState);
        }
        
        private void OnGetContactPrivilegeOperationCompleted(object arg) {
            if ((this.GetContactPrivilegeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContactPrivilegeCompleted(this, new GetContactPrivilegeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountPrimarySales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT GetAccountPrimarySales(string LoginID, string AccountId) {
            object[] results = this.Invoke("GetAccountPrimarySales", new object[] {
                        LoginID,
                        AccountId});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountPrimarySalesAsync(string LoginID, string AccountId) {
            this.GetAccountPrimarySalesAsync(LoginID, AccountId, null);
        }
        
        /// <remarks/>
        public void GetAccountPrimarySalesAsync(string LoginID, string AccountId, object userState) {
            if ((this.GetAccountPrimarySalesOperationCompleted == null)) {
                this.GetAccountPrimarySalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountPrimarySalesOperationCompleted);
            }
            this.InvokeAsync("GetAccountPrimarySales", new object[] {
                        LoginID,
                        AccountId}, this.GetAccountPrimarySalesOperationCompleted, userState);
        }
        
        private void OnGetAccountPrimarySalesOperationCompleted(object arg) {
            if ((this.GetAccountPrimarySalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountPrimarySalesCompleted(this, new GetAccountPrimarySalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountContactAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT GetAccountContactAdmin(string LoginID, string AccountId) {
            object[] results = this.Invoke("GetAccountContactAdmin", new object[] {
                        LoginID,
                        AccountId});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountContactAdminAsync(string LoginID, string AccountId) {
            this.GetAccountContactAdminAsync(LoginID, AccountId, null);
        }
        
        /// <remarks/>
        public void GetAccountContactAdminAsync(string LoginID, string AccountId, object userState) {
            if ((this.GetAccountContactAdminOperationCompleted == null)) {
                this.GetAccountContactAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountContactAdminOperationCompleted);
            }
            this.InvokeAsync("GetAccountContactAdmin", new object[] {
                        LoginID,
                        AccountId}, this.GetAccountContactAdminOperationCompleted, userState);
        }
        
        private void OnGetAccountContactAdminOperationCompleted(object arg) {
            if ((this.GetAccountContactAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountContactAdminCompleted(this, new GetAccountContactAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSRUnderAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT GetSRUnderAccount(string LoginID, string AccountId, string Type) {
            object[] results = this.Invoke("GetSRUnderAccount", new object[] {
                        LoginID,
                        AccountId,
                        Type});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetSRUnderAccountAsync(string LoginID, string AccountId, string Type) {
            this.GetSRUnderAccountAsync(LoginID, AccountId, Type, null);
        }
        
        /// <remarks/>
        public void GetSRUnderAccountAsync(string LoginID, string AccountId, string Type, object userState) {
            if ((this.GetSRUnderAccountOperationCompleted == null)) {
                this.GetSRUnderAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSRUnderAccountOperationCompleted);
            }
            this.InvokeAsync("GetSRUnderAccount", new object[] {
                        LoginID,
                        AccountId,
                        Type}, this.GetSRUnderAccountOperationCompleted, userState);
        }
        
        private void OnGetSRUnderAccountOperationCompleted(object arg) {
            if ((this.GetSRUnderAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSRUnderAccountCompleted(this, new GetSRUnderAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActivitiesUnderSR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT GetActivitiesUnderSR(string LoginID, string SRNum, string Type) {
            object[] results = this.Invoke("GetActivitiesUnderSR", new object[] {
                        LoginID,
                        SRNum,
                        Type});
            return ((RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetActivitiesUnderSRAsync(string LoginID, string SRNum, string Type) {
            this.GetActivitiesUnderSRAsync(LoginID, SRNum, Type, null);
        }
        
        /// <remarks/>
        public void GetActivitiesUnderSRAsync(string LoginID, string SRNum, string Type, object userState) {
            if ((this.GetActivitiesUnderSROperationCompleted == null)) {
                this.GetActivitiesUnderSROperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActivitiesUnderSROperationCompleted);
            }
            this.InvokeAsync("GetActivitiesUnderSR", new object[] {
                        LoginID,
                        SRNum,
                        Type}, this.GetActivitiesUnderSROperationCompleted, userState);
        }
        
        private void OnGetActivitiesUnderSROperationCompleted(object arg) {
            if ((this.GetActivitiesUnderSRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActivitiesUnderSRCompleted(this, new GetActivitiesUnderSRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RESULT {
        
        private string rOW_IDField;
        
        private string eRR_MSGField;
        
        private string rESULT_AField;
        
        private bool iS_COMMITTEDField;
        
        private System.Data.DataSet rETURN_LISTField;
        
        private System.Data.DataTable rETURN_TABLEField;
        
        /// <remarks/>
        public string ROW_ID {
            get {
                return this.rOW_IDField;
            }
            set {
                this.rOW_IDField = value;
            }
        }
        
        /// <remarks/>
        public string ERR_MSG {
            get {
                return this.eRR_MSGField;
            }
            set {
                this.eRR_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string RESULT_A {
            get {
                return this.rESULT_AField;
            }
            set {
                this.rESULT_AField = value;
            }
        }
        
        /// <remarks/>
        public bool IS_COMMITTED {
            get {
                return this.iS_COMMITTEDField;
            }
            set {
                this.iS_COMMITTEDField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet RETURN_LIST {
            get {
                return this.rETURN_LISTField;
            }
            set {
                this.rETURN_LISTField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable RETURN_TABLE {
            get {
                return this.rETURN_TABLEField;
            }
            set {
                this.rETURN_TABLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckContactCompletedEventHandler(object sender, CheckContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckEmployeeCompletedEventHandler(object sender, CheckEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckPositionCompletedEventHandler(object sender, CheckPositionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSRInformationCompletedEventHandler(object sender, GetSRInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSRInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSRInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckProductCompletedEventHandler(object sender, CheckProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetContactListunderAccountCompletedEventHandler(object sender, GetContactListunderAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContactListunderAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContactListunderAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetContactPrivilegeCompletedEventHandler(object sender, GetContactPrivilegeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContactPrivilegeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContactPrivilegeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAccountPrimarySalesCompletedEventHandler(object sender, GetAccountPrimarySalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountPrimarySalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountPrimarySalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAccountContactAdminCompletedEventHandler(object sender, GetAccountContactAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountContactAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountContactAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSRUnderAccountCompletedEventHandler(object sender, GetSRUnderAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSRUnderAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSRUnderAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetActivitiesUnderSRCompletedEventHandler(object sender, GetActivitiesUnderSRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActivitiesUnderSRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActivitiesUnderSRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591